name: Ensure Bug Reports Include Reproduction Steps

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  require-repro-steps:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.labels.*.name contains 'bug'
    steps:
      - name: Check for reproduction steps in bug report
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body;
            if (!body || !body.toLowerCase().includes('steps to reproduce')) {
              core.setFailed('Bug report is missing reproduction steps. Please include a \"Steps to reproduce\" section.');
            }
